# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target :'Drop' do
    pod 'AWSCore', '~> 2.6.6’
    pod 'AWSMobileClient', '~> 2.6.6'
    pod 'AWSUserPoolsSignIn', '~> 2.6.6'
    pod 'AWSDynamoDB', '~> 2.6.1'
        

    target 'DropTests' do
        inherit! :search_paths
        pod 'AWSCognitoIdentityProvider', '~> 2.6.6'
    end
end
