//
//  AccountInfo.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class AccountInfo: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _accountName: String?
    var _firstName: String?
    var _friends: [String]?
    var _lastName: String?
    var _profilePhoto: String?
    
    class func dynamoDBTableName() -> String {

        return "airsplit-mobilehub-2093393909-Account_info"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_accountName"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_accountName" : "accountName",
               "_firstName" : "firstName",
               "_friends" : "friends",
               "_lastName" : "lastName",
               "_profilePhoto" : "profilePhoto",
        ]
    }
}
