//
//  Transanctions.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.19
//

import Foundation
import UIKit
import AWSDynamoDB

class Transanctions: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _transactionId: String?
    var _transactionDate: String?
    var _borrower: NSNumber?
    var _lender: NSNumber?
    
    class func dynamoDBTableName() -> String {

        return "airsplit-mobilehub-2093393909-Transanctions"
    }
    
    class func hashKeyAttribute() -> String {

        return "_transactionId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_transactionDate"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_transactionId" : "transactionId",
               "_transactionDate" : "transactionDate",
               "_borrower" : "borrower",
               "_lender" : "lender",
        ]
    }
}
